In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('train.txt',sep = ';',header = None , names = ['text','emotions'])

In [3]:
df.head()

                                                text emotions
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [4]:
df.isnull().sum()

text        0
emotions    0
dtype: int64

In [5]:
unique_emotions = df['emotions'].unique()

In [6]:
unique_emotions

array(['sadness', 'anger', 'love', 'surprise', 'fear', 'joy'],
      dtype=object)

In [7]:
emotion_number = {}
i = 0
for emo in unique_emotions:
    emotion_number[emo] = i
    i+=1

df['emotions'] = df['emotions'].map(emotion_number)

In [8]:
df

                                                    text  emotions
0                                i didnt feel humiliated         0
1      i can go from feeling so hopeless to so damned...         0
2       im grabbing a minute to post i feel greedy wrong         1
3      i am ever feeling nostalgic about the fireplac...         2
4                                   i am feeling grouchy         1
...                                                  ...       ...
15995  i just had a very brief time in the beanbag an...         0
15996  i am now turning and i feel pathetic that i am...         0
15997                     i feel strong and good overall         5
15998  i feel like this was such a rude comment and i...         1
15999  i know a lot but i feel so stupid because i ca...         0

[16000 rows x 2 columns]

In [9]:
df['text'] = df['text'].apply(lambda x : x.lower())

In [10]:
df

                                                    text  emotions
0                                i didnt feel humiliated         0
1      i can go from feeling so hopeless to so damned...         0
2       im grabbing a minute to post i feel greedy wrong         1
3      i am ever feeling nostalgic about the fireplac...         2
4                                   i am feeling grouchy         1
...                                                  ...       ...
15995  i just had a very brief time in the beanbag an...         0
15996  i am now turning and i feel pathetic that i am...         0
15997                     i feel strong and good overall         5
15998  i feel like this was such a rude comment and i...         1
15999  i know a lot but i feel so stupid because i ca...         0

[16000 rows x 2 columns]

In [11]:
import string
def remove_punc(txt):
    return txt.translate(str.maketrans('','',string.punctuation))

In [12]:
df['text'] = df['text'].apply(remove_punc)

In [13]:
df

                                                    text  emotions
0                                i didnt feel humiliated         0
1      i can go from feeling so hopeless to so damned...         0
2       im grabbing a minute to post i feel greedy wrong         1
3      i am ever feeling nostalgic about the fireplac...         2
4                                   i am feeling grouchy         1
...                                                  ...       ...
15995  i just had a very brief time in the beanbag an...         0
15996  i am now turning and i feel pathetic that i am...         0
15997                     i feel strong and good overall         5
15998  i feel like this was such a rude comment and i...         1
15999  i know a lot but i feel so stupid because i ca...         0

[16000 rows x 2 columns]

In [14]:
import re

df["text"] = df["text"].apply(lambda x: re.sub(r"\d+", "", x))

In [15]:
df

                                                    text  emotions
0                                i didnt feel humiliated         0
1      i can go from feeling so hopeless to so damned...         0
2       im grabbing a minute to post i feel greedy wrong         1
3      i am ever feeling nostalgic about the fireplac...         2
4                                   i am feeling grouchy         1
...                                                  ...       ...
15995  i just had a very brief time in the beanbag an...         0
15996  i am now turning and i feel pathetic that i am...         0
15997                     i feel strong and good overall         5
15998  i feel like this was such a rude comment and i...         1
15999  i know a lot but i feel so stupid because i ca...         0

[16000 rows x 2 columns]

In [16]:
def remove_emoji(txt):
    new = ""
    for ch in txt:
        if ch.isascii():
            new += ch
    return new

df["text"] = df["text"].apply(remove_emoji)

In [17]:
df

                                                    text  emotions
0                                i didnt feel humiliated         0
1      i can go from feeling so hopeless to so damned...         0
2       im grabbing a minute to post i feel greedy wrong         1
3      i am ever feeling nostalgic about the fireplac...         2
4                                   i am feeling grouchy         1
...                                                  ...       ...
15995  i just had a very brief time in the beanbag an...         0
15996  i am now turning and i feel pathetic that i am...         0
15997                     i feel strong and good overall         5
15998  i feel like this was such a rude comment and i...         1
15999  i know a lot but i feel so stupid because i ca...         0

[16000 rows x 2 columns]

In [18]:
import nltk

In [19]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [20]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\mbgop\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\mbgop\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [21]:
import nltk

nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\mbgop\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [22]:
stop_words = set(stopwords.words('english'))
len(stop_words)

198

In [23]:
df.loc[1]['text']

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [24]:
from nltk.tokenize import word_tokenize

def remove(txt):
    words = word_tokenize(txt)
    cleaned = []

    for word in words:
        if word not in stop_words:
            cleaned.append(word)

    return " ".join(cleaned)

df["text"] = df["text"].apply(remove)

In [26]:
df

                                                    text  emotions
0                                  didnt feel humiliated         0
1      go feeling hopeless damned hopeful around some...         0
2              im grabbing minute post feel greedy wrong         1
3      ever feeling nostalgic fireplace know still pr...         2
4                                        feeling grouchy         1
...                                                  ...       ...
15995      brief time beanbag said anna feel like beaten         0
15996  turning feel pathetic still waiting tables sub...         0
15997                           feel strong good overall         5
15998                     feel like rude comment im glad         1
15999                       know lot feel stupid portray         0

[16000 rows x 2 columns]

In [27]:
import nltk
print(nltk.__version__)

3.9.1

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
X = df['text']
y = df['emotions']

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [32]:
X_train.shape

(12800,)

In [59]:
from sklearn.feature_extraction.text import TfidfVectorizer , CountVectorizer

In [60]:
bow_vectorizer = CountVectorizer()

In [61]:
X_train_bow = bow_vectorizer.fit_transform(X_train)

In [62]:
X_test_bow = bow_vectorizer.transform(X_test)

In [63]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

In [64]:
nb_model = MultinomialNB()

In [65]:
nb_model.fit(X_train_bow,y_train)

MultinomialNB()

In [67]:
pred_nb = nb_model.predict(X_test_bow)

In [68]:
accuracy = accuracy_score(y_test,pred_nb)

In [69]:
accuracy

0.7678125

In [82]:
tfidf_vectorizer = TfidfVectorizer()

X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

nb2_model = MultinomialNB()
nb2_model.fit(X_train_tfidf, y_train)

MultinomialNB()

In [83]:
pred_tfidf = nb_model.predict(X_test_tfidf)

In [84]:
accuracy = accuracy_score(y_test,pred_tfidf)

In [85]:
accuracy

0.6609375

# 🔥 Best Model Selection (Final)

This section trains multiple NLP classifiers on the TF-IDF features and automatically selects the highest accuracy model.

**Models compared**
- Linear SVM ⭐
- Logistic Regression
- SGD Classifier
- Multinomial Naive Bayes
- Random Forest

The notebook prints the accuracy of each model, displays a sorted comparison table, and keeps the best model for prediction.

In [ ]:
from sklearn.svm import LinearSVC
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
import pandas as pd
import joblib

# Optimized TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer(
    lowercase=True,
    stop_words='english',
    ngram_range=(1,2),
    min_df=2,
    max_df=0.95,
    sublinear_tf=True
)

X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

models = {
    "Linear SVM": LinearSVC(),
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "SGD Classifier": SGDClassifier(random_state=42),
    "Multinomial NB": MultinomialNB(),
    "Random Forest": RandomForestClassifier(
        n_estimators=200,
        random_state=42
    )
}

results = {}
trained_models = {}

for name, model in models.items():
    model.fit(X_train_tfidf, y_train)
    pred = model.predict(X_test_tfidf)
    acc = accuracy_score(y_test, pred)

    results[name] = acc
    trained_models[name] = model

    print(f"{name:22} : {acc:.4f}")

result_df = pd.DataFrame({
    "Model": results.keys(),
    "Accuracy": results.values()
}).sort_values(by="Accuracy", ascending=False)

print("\n🏆 Best Model")
best_model_name = result_df.iloc[0]["Model"]
best_model = trained_models[best_model_name]

print("Model :", best_model_name)
print("Accuracy :", result_df.iloc[0]["Accuracy"])

display(result_df)

# Detailed report
best_pred = best_model.predict(X_test_tfidf)
print("\nClassification Report\n")
print(classification_report(y_test, best_pred))

# Save model + vectorizer
joblib.dump(best_model, "best_nlp_model.pkl")
joblib.dump(tfidf_vectorizer, "tfidf_vectorizer.pkl")

print("\n✅ Saved: best_nlp_model.pkl")
print("✅ Saved: tfidf_vectorizer.pkl")

In [ ]:
# Test your own sentence

text = ["i am feeling extremely happy today"]

vector = tfidf_vectorizer.transform(text)
prediction = best_model.predict(vector)

print("Sentence :", text[0])
print("Predicted Emotion :", prediction[0])